project:
  type: website
  output-dir: docs

website:
  title: "BMECM"
  sidebar:
    background: "#285c34"
    style: "docked"
    search: true
    collapse-level: 1
    contents:
      - href: index.qmd
        text: Home
      - about.qmd
      - href: index.qmd
      - href: geometria_vetores.qmd
      - href: comprimento_angulo.qmd
      - href: sistema_equacoes_lineares.qmd
      - href: matrizes.qmd
      

format:
  html:
    theme: [cosmo, custom.scss]
    #css: styles.css
    #css: custom.scss
    toc: true
  revealjs:
    theme: [serif, custom.scss]
    menu: false
    progress: false

freeze: false


