---
title: "Matrizes"
subtitle: "Aplicações"
institute: "9833 - BASES DA MATEMÁTICA E ESTATÍSTICA PARA CIÊNCIAS DO MAR"
author: 	"Fabio Cop Ferreira e William Remo Pedroso Conti"
format:
  revealjs: 
    slide-number: true
    chalkboard: 
      buttons: false
    preview-links: auto
    logo: imagens/BMEC-Mar-icon.png
    footer: BICT Mar - Unifesp
---

## Exemplo de aplicação: Cadeias de Markov para Recifes de Coral

::: {style="font-size: .7em"}

**Problema**

Os recifes de coral enfrentam várias ameaças ambientais, como branqueamento, acidificação dos oceanos e destruição física. Essas ameaças podem ser modeladas usando uma Cadeia de Markov para entender a probabilidade de um recife estar em um certo estado de saúde ao longo do tempo.

**Estados**

Definimos três estados possíveis para a saúde de um recife de coral:

- **S1:** Saudável
- **S2:** Moderadamente Degradado
- **S3:** Severamente Degradado

**Matriz de Transição**

A matriz de transição de estados, $P$, representa as probabilidades de transição entre os estados de saúde de um recife de coral de um período para o outro.

$$P = \begin{bmatrix}
0.7 & 0.2 & 0.1 \\
0.3 & 0.5 & 0.2 \\
0.1 & 0.3 & 0.6
\end{bmatrix}$$

Cada elemento $P_{ij}$ na matriz representa a probabilidade de transição do estado $i$ para o estado $j$. Por exemplo, $P_{12} = 0.2$ indica que há uma probabilidade de 20% de um recife saudável ($S1$) passar para o estado moderadamente degradado ($S2$) no próximo período.

:::

## Exemplo de aplicação: Cadeias de Markov para Recifes de Coral

::: {style="font-size: .7em"}

Vamos considerar que inicialmente 80% dos recifes estão saudáveis, 15% estão moderadamente degradados e 5% estão severamente degradados. Isso pode ser representado pelo vetor de estado inicial:

$$\vec{v_0} = \begin{bmatrix}
0.8 \\
0.15 \\
0.05
\end{bmatrix}$$

Para determinar o estado dos recifes após um período, multiplicamos o vetor de estado inicial pela matriz de transição:

$$\vec{v_1} = \vec{v_0} \times P = \begin{bmatrix}
0.8 & 0.15 & 0.05
\end{bmatrix} \times \begin{bmatrix}
0.7 & 0.2 & 0.1 \\
0.3 & 0.5 & 0.2 \\
0.1 & 0.3 & 0.6
\end{bmatrix}$$

Calculando:

$$\vec{v_1} = \begin{bmatrix}
0.8(0.7) + 0.15(0.3) + 0.05(0.1) \\
0.8(0.2) + 0.15(0.5) + 0.05(0.3) \\
0.8(0.1) + 0.15(0.2) + 0.05(0.6)
\end{bmatrix} = \begin{bmatrix}
0.635 \\
0.2425 \\
0.1225
\end{bmatrix}$$

Isso indica que, após um período, aproximadamente 63,5% dos recifes estarão saudáveis, 24,25% estarão moderadamente degradados, e 12,25% estarão severamente degradados.

:::

## Exemplo de aplicação: Cadeias de Markov para Recifes de Coral

::: {style="font-size: .7em"}

**Estado Estacionário**

O estado estacionário é um vetor de probabilidades que representa a distribuição dos estados de um sistema em equilíbrio, onde as probabilidades de estar em cada estado não mudam com o tempo. Para uma cadeia de Markov, isso ocorre quando o vetor de estado não muda após uma multiplicação pela matriz de transição.

**Propriedade:** Se $\vec{v}$ é um vetor de estado estacionário e $P$ é a matriz de transição, então:
  
  $$ \vec{v} \times P = \vec{v} $$

Isso significa que a multiplicação do vetor de estado estacionário pela matriz de transição retorna o mesmo vetor.

Vamos continuar com a matriz de transição $P$ que definimos anteriormente:

$$P = \begin{bmatrix}
0.7 & 0.2 & 0.1 \\
0.3 & 0.5 & 0.2 \\
0.1 & 0.3 & 0.6
\end{bmatrix}$$

Para encontrar o vetor de estado estacionário $\vec{v}_{ss}$, resolvemos a equação:

$$ \vec{v}_{ss} \times P = \vec{v}_{ss} $$

em que

$\vec{v}_{ss} = \begin{bmatrix}
\pi_1 \\
\pi_2 \\
\pi_3
\end{bmatrix}$

:::

## Exemplo de aplicação: Cadeias de Markov para Recifes de Coral

::: {style="font-size: .7em"}

Para encontrar o vetor de estado estacionário $\vec{v}_{ss}$, precisamos resolver:

$$
\vec{v}_{ss} \times P = \vec{v}_{ss}
$$

Ou seja,

$$
\begin{bmatrix}
\pi_1 & \pi_2 & \pi_3
\end{bmatrix} \times \begin{bmatrix}
0.7 & 0.2 & 0.1 \\
0.3 & 0.5 & 0.2 \\
0.1 & 0.3 & 0.6
\end{bmatrix} = \begin{bmatrix}
\pi_1 & \pi_2 & \pi_3
\end{bmatrix}
$$

:::: columns

::: {.column}

Isso gera o sistema de equações:

$\begin{cases}
\pi_1 \cdot 0.7 + \pi_2 \cdot 0.3 + \pi_3 \cdot 0.1 &= \pi_1 \\
\pi_1 \cdot 0.2 + \pi_2 \cdot 0.5 + \pi_3 \cdot 0.3 &= \pi_2 \\
\pi_1 \cdot 0.1 + \pi_2 \cdot 0.2 + \pi_3 \cdot 0.6 &= \pi_3
\end{cases}$

:::

::: {.column}

Que simplificado fica:

$\begin{cases}
-0.3\pi_1 + 0.3\pi_2 + 0.1\pi_3 = 0 \\
0.2\pi_1 - 0.5\pi_2 + 0.3\pi_3 = 0 \\
0.1\pi_1 + 0.2\pi_2 - 0.4\pi_3 = 0
\end{cases}$


:::

::::

:::

## Exemplo de aplicação: Cadeias de Markov para Recifes de Coral

::: {style="font-size: .7em"}


Há ainda uma condição adicional de que a soma das probabilidades seja 1, portanto $\pi_1 + \pi_2 + \pi_3 = 1$

De modo que:

$$\begin{cases}
-0.3\pi_1 + 0.3\pi_2 + 0.1\pi_3 = 0 \\
0.2\pi_1 - 0.5\pi_2 + 0.3\pi_3 = 0 \\
0.1\pi_1 + 0.2\pi_2 - 0.4\pi_3 = 0 \\
\pi_1 + \pi_2 + \pi_3 = 1
\end{cases}$$


Utilizando métodos algébricos, no estado estacionário, a distribuição das probabilidades entre os estados será ([Link para resolução completa](https://github.com/FCopf/apresentacoes/blob/master/docs/Cadeias-de-Markov-para-Recifes-de-Coral.pdf)):

$\pi_1 = \frac{7}{17} ~ \sim 0.4117$

$\pi_2 = \frac{11}{34} ~ \sim 0.3235$

$\pi_3 = \frac{9}{34} ~ \sim 0.2647$

:::

::: {.callout-tip title="Conclusão"}

A existência de um vetor estacionário indica que, independentemente do estado inicial, a cadeia de Markov converge para essa distribuição de probabilidade quando o sistema está em equilíbrio.

Portanto, mantendo as condições atuais que resultam na matriz de transição vigente, espera-se que, a longo prazo, aproximadamente 41,18% do recife de coral permanecerá em condições *Saudáveis*, 32,35% estará *Moderadamente Degradado* e 26,47% será *Severamente Degradado*.


:::


## Discussão e aplicações: Crescimento populacional

- **Modelo:** Utilização de matrizes para modelar a dinâmica populacional.
- **Exemplo:** Modelos de Leslie.



